services:
  eureka-server:
    image: eclipse-temurin:17-jdk
    container_name: stark-eureka
    working_dir: /app
    volumes:
      - ./starkDistribuidos-config/target/stark-config-0.0.1-SNAPSHOT.jar:/app/eureka.jar
    ports:
      - "8761:8761"
    command: java -jar eureka.jar
    networks:
      - stark-network

  api-gateway:
    image: eclipse-temurin:17-jdk
    container_name: stark-gateway
    working_dir: /app
    volumes:
      - ./starkDistribuidos-gateway/target/stark-gateway-0.0.1-SNAPSHOT.jar:/app/gateway.jar
    ports:
      - "8080:8080"
    command: java -jar gateway.jar
    depends_on:
      - eureka-server
    networks:
      - stark-network

  auth-service:
    image: eclipse-temurin:17-jdk
    container_name: stark-auth
    working_dir: /app
    volumes:
      - ./starkDistribuidos-auth/target/stark-auth-0.0.1-SNAPSHOT.jar:/app/auth.jar
    ports:
      - "8081:8081"
    command: java -jar auth.jar
    depends_on:
      - eureka-server
    networks:
      - stark-network

  sensor-service:
    image: eclipse-temurin:17-jdk
    container_name: stark-sensor
    working_dir: /app
    volumes:
      - ./starkDistribuidos-sensor/target/stark-sensor-0.0.1-SNAPSHOT.jar:/app/sensor.jar
    ports:
      - "8082:8082"
    command: java -jar sensor.jar
    depends_on:
      - eureka-server
    networks:
      - stark-network

  alert-service:
    image: eclipse-temurin:17-jdk
    container_name: stark-alert
    working_dir: /app
    volumes:
      - ./starkDistribuidos-alert/target/stark-alert-0.0.1-SNAPSHOT.jar:/app/alert.jar
    ports:
      - "8083:8083"
    command: java -jar alert.jar
    depends_on:
      - eureka-server
    networks:
      - stark-network

  access-service:
    image: eclipse-temurin:17-jdk
    container_name: stark-access
    working_dir: /app
    volumes:
      - ./starkDistribuidos-access/target/stark-access-0.0.1-SNAPSHOT.jar:/app/access.jar
    ports:
      - "8084:8084"
    command: java -jar access.jar
    depends_on:
      - eureka-server
    networks:
      - stark-network

  notification-service:
    image: eclipse-temurin:17-jdk
    container_name: stark-notification
    working_dir: /app
    volumes:
      - ./starkDistribuidos-notification/target/stark-notification-0.0.1-SNAPSHOT.jar:/app/notification.jar
      - notification-data:/app/data
    ports:
      - "8086:8086"
    command: java -jar notification.jar
    depends_on:
      - eureka-server
    networks:
      - stark-network

networks:
  stark-network:
    driver: bridge

volumes:
  notification-data: