spring:
  application:
    name: stark-notification
  mail:
    host: smtp.gmail.com
    port: 587
    username: mypillsfp@gmail.com
    password: kfqulbdlzxppemzy
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@127.0.0.1:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8085

