spring:
  application:
    name: stark-sensor
  datasource:
    url: jdbc:h2:mem:sensordb
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8082





