spring:
  application:
    name: stark-gateway
  cloud:
    gateway:
      routes:
        - id: sensor-service
          uri: lb://stark-sensor
          predicates:
            - Path=/api/sensors/**
        - id: alert-service
          uri: lb://stark-alert
          predicates:
            - Path=/api/alerts/**
        - id: access-service
          uri: lb://stark-access
          predicates:
            - Path=/api/access/**
        - id: notification-service
          uri: lb://stark-notification
          predicates:
            - Path=/api/notifications/**
        - id: auth-service
          uri: lb://stark-auth
          predicates:
            - Path=/api/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8080